title: Real-View-On-Releases
description: Habilita RealView en SolidWorks y soluciona errores gráficos.
baseurl: "/Real-View-On-Releases"
url: "https://ianalexis.github.io"
remote_theme: pages-themes/hacker@v0.2.0
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme