# Workflow para compilar el proyecto RealViewOn con MSBuild
# Este workflow compila el proyecto C++ para arquitecturas x86 y x64

name: Build RealViewOn

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: RealViewOn.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup Visual Studio components
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          rtmidi/lib/
          midifile/
        key: ${{ runner.os }}-deps-${{ hashFiles('**/rtmidi/**', '**/midifile/**') }}

    - name: Build x64
      run: |
        msbuild ${{ env.SOLUTION_FILE_PATH }} `
          /p:Configuration=${{ env.BUILD_CONFIGURATION }} `
          /p:Platform=x64 `
          /p:PlatformToolset=ClangCL `
          /p:WindowsTargetPlatformVersion=10.0.22621.0 `
          /p:UseMultiToolTask=true `
          /p:EnforceProcessCountAcrossBuilds=true `
          /maxcpucount `
          /verbosity:minimal

    - name: Test executable exists
      run: |
        $exePath = "x64\Release\RealViewOn.exe"
        
        if (Test-Path $exePath) {
          Write-Host "✅ Executable found: $exePath"
          Get-Item $exePath | Select-Object Name, Length, LastWriteTime
        } else {
          Write-Host "❌ Executable not found: $exePath"
          exit 1
        }

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RealViewOn-x64-${{ env.BUILD_CONFIGURATION }}
        path: |
          x64/Release/RealViewOn.exe
          x64/Release/*.pdb
        if-no-files-found: ignore

  release:
    needs: build
    runs-on: windows-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code (for UPX tool)
      uses: actions/checkout@v4
      
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: List downloaded artifacts
      run: |
        Write-Host "Contenido del workspace después de descargar artefactos:"
        Get-ChildItem -Recurse | Select-Object FullName, Length
      
    - name: Create release package
      run: |
        New-Item -ItemType Directory -Path "release-package" -Force
        
        # Buscar el ejecutable en todas las ubicaciones posibles
        $possiblePaths = @(
          "RealViewOn-x64-Release\x64\Release\RealViewOn.exe",
          "RealViewOn-x64-Release\RealViewOn.exe",
          "x64\Release\RealViewOn.exe",
          "RealViewOn.exe"
        )
        
        $found = $false
        $sourceExe = ""
        foreach ($path in $possiblePaths) {
          if (Test-Path $path) {
            Write-Host "✅ Encontrado ejecutable en: $path"
            $sourceExe = $path
            $found = $true
            break
          }
        }
        
        if (-not $found) {
          Write-Host "❌ No se encontró el ejecutable en ninguna ubicación"
          Write-Host "Estructura de directorios actual:"
          Get-ChildItem -Recurse | Where-Object { $_.Name -like "*.exe" } | Select-Object FullName
          exit 1
        }
        
        # Copiar ejecutable a release-package
        Copy-Item $sourceExe "release-package\RealViewOn.exe"
        
        # Comprimir con UPX si existe
        if (Test-Path "tools\upx.exe") {
          Write-Host "🗜️ Comprimiendo con UPX..."
          $originalSize = (Get-Item "release-package\RealViewOn.exe").Length
          Write-Host "Tamaño original: $([math]::Round($originalSize/1MB, 2)) MB"
          
          & ".\tools\upx.exe" --ultra-brute "release-package\RealViewOn.exe"
          
          if ($LASTEXITCODE -eq 0) {
            $compressedSize = (Get-Item "release-package\RealViewOn.exe").Length
            $compressionRatio = [math]::Round((($originalSize - $compressedSize) / $originalSize) * 100, 1)
            Write-Host "✅ Compresión UPX completada"
            Write-Host "Tamaño comprimido: $([math]::Round($compressedSize/1MB, 2)) MB"
            Write-Host "Reducción: $compressionRatio%"
          } else {
            Write-Host "⚠️ Error en compresión UPX, continuando sin comprimir"
          }
        } else {
          Write-Host "⚠️ UPX no encontrado, saltando compresión"
        }
        
        # Listar contenido del paquete final
        Write-Host "Contenido del paquete de release:"
        Get-ChildItem "release-package" -Recurse | Select-Object Name, Length

    - name: Upload release package
      uses: actions/upload-artifact@v4
      with:
        name: RealViewOn-Release-Package
        path: release-package/
        if-no-files-found: error
